site_name: My Documentation
theme: readthedocs
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage: usage.md
  - API Reference:
    - Overview: api.md
    - Examples: examples.md
site_name: My Documentation
theme: readthedocs
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage: usage.md
  - API Reference:
    - Overview: api.md
    - Examples: examples.md
